name: Toronto Dashboard (2hr)

on:
schedule:
- cron: '0 */2 * * *'
workflow_dispatch:

jobs:
screenshot-and-send:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repo
    uses: actions/checkout@v3

  - name: Install dependencies
    run: npm install

  - name: Run screenshot script
    env:
      DASHBOARD_URL: "https://metabase.spyne.ai/public/dashboard/ef9401fb-cb84-4228-add3-009dc09b1037?date=thismonth&enterpriseid=82255fce5"
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
    run: node screenshot.js
```
