name: Toronto Dashboard

on:
schedule:
- cron: '0 */2 * * *'
workflow_dispatch:

jobs:
run-script:
runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Install Node
    uses: actions/setup-node@v3
    with:
      node-version: '18'

  - name: Install Chromium
    run: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser

  - name: Install dependencies
    run: npm install
    env:
      PUPPETEER_SKIP_DOWNLOAD: true

  - name: Run script
    run: node screenshot.js
    env:
      DASHBOARD_URL: https://metabase.spyne.ai/public/dashboard/ef9401fb-cb84-4228-add3-009dc09b1037?date=thismonth&enterpriseid=82255fce5
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
```
